### ISSUE TITLE
Building the ipp image hangs in Step 5/11 : RUN pip install -e . 

### ISSUE THREAD

**Issue by abdelkhalek-mohamed** [NVIDIA/ipyparaview#28]
`docker build -t ipp .` hangs in step 5/11 in `Obtaining file:///root/ipyparaview` using `docker run -t -i ipp` and running the pip install step manually hangs as well, interrupting the process shows the following the following trace

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/opt/conda/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/opt/conda/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError`

Thanks

**Comment by abdelkhalek-mohamed** [comment]
Seems to have been an internet issue, it just takes a long time
