### ISSUE TITLE
RuntimeError: npm dependencies failed to install

### ISSUE THREAD

**Issue by apaaris** [NVIDIA/ipyparaview#39]
Dear everyone, everytime that I get to the last step of the installation something fails
```
$ jupyter labextension install js
```
I tried installing everything manually, both globally and locally with:
```
npm i @jupyter-widgets/base@^1.1 -g
```
But it still won't find the installed package, however, I am not sure if this depends on npm or on the install procedure

Here is my log file
```
Node v16.14.2

Yarn configuration loaded.
> "C:\Program Files\nodejs\npm.CMD" pack C:\Users\*user*\ipyparaview\js
npm notice 
npm notice package: ipyparaview@0.1.2
npm notice === Tarball Contents === 
npm notice 198B    README.md       
npm notice 557.7kB dist/index.js   
npm notice 461B    lib/embed.js    
npm notice 842B    lib/extension.js
npm notice 180B    lib/index.js    
npm notice 375B    lib/labplugin.js
npm notice 8.0kB   lib/widgets.js  
npm notice 919B    package.json    
npm notice === Tarball Details === 
npm notice name:          ipyparaview                             
npm notice version:       0.1.2                                   
npm notice filename:      ipyparaview-0.1.2.tgz                   
npm notice package size:  103.4 kB                                
npm notice unpacked size: 568.6 kB                                
npm notice shasum:        2c1fa1e2abb0b841c677847bc31626591d56aa68
npm notice integrity:     sha512-Qe1PWE7HHyB8s[...]AqUIvGInKhBWQ==
npm notice total files:   8                                       
npm notice 
ipyparaview-0.1.2.tgz

Node v16.14.2

Yarn configuration loaded.
Building jupyterlab assets (development)
> "C:\Program Files\nodejs\npm.CMD" pack C:\Users\*user*\ipyparaview\js
npm notice 
npm notice package: ipyparaview@0.1.2
npm notice === Tarball Contents === 
npm notice 198B    README.md       
npm notice 557.7kB dist/index.js   
npm notice 461B    lib/embed.js    
npm notice 842B    lib/extension.js
npm notice 180B    lib/index.js    
npm notice 375B    lib/labplugin.js
npm notice 8.0kB   lib/widgets.js  
npm notice 919B    package.json    
npm notice === Tarball Details === 
npm notice name:          ipyparaview                             
npm notice version:       0.1.2                                   
npm notice filename:      ipyparaview-0.1.2.tgz                   
npm notice package size:  103.4 kB                                
npm notice unpacked size: 568.6 kB                                
npm notice shasum:        2c1fa1e2abb0b841c677847bc31626591d56aa68
npm notice integrity:     sha512-Qe1PWE7HHyB8s[...]AqUIvGInKhBWQ==
npm notice total files:   8                                       
npm notice 
ipyparaview-0.1.2.tgz

> node C:\Users\*user*\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@jupyter-widgets/base@^1.1 || ^2 || ^3" required by "ipyparaview@file:C:\\Users\\*user*\\Anaconda3\\share\\jupyter\\lab\\extensions\\ipyparaview-0.1.2-8d89fa4ad9c4c49d51d2e1fccf9fa57a519be217.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "C:\Users\*user*\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 48, in debug_logging
    yield

  File "C:\Users\*user*\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 140, in start
    build(clean_staging=self.should_clean,

  File "C:\Users\*user*\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "C:\Users\*user*\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 688, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: lab
```

**Comment by apaaris** [comment]
```
yarn config set strict-ssl false
```

Made it for me
